jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      name: Build with Maven
      run: mvn --batch-mode --file pom.xml package
name: Maven build
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
